/**
 * ConsiderationsSynthesizer — event-aware "Related from your brain" producer.
 *
 * Replaces the previous (semantic-search → relevance-filter → render
 * raw snippets) pipeline with a synthesis step that turns scattered
 * brain items into one 1–3 sentence paragraph specific to the event.
 *
 * Two strategies, dispatched by event type:
 *
 *  birthday  - Targeted: extract the person's name from the summary,
 *              run brain queries about gift ideas / interests /
 *              personality / preferences. Prompt explicitly
 *              de-prioritizes location and Google-activity history
 *              (per user feedback 2026-05-28: "looking for notes on
 *              gift ideas is more relevant or personality notes (if
 *              any) over locations unless deliberately stated").
 *
 *  generic   - Query the brain by event title + description and ask
 *              the LLM to bridge connections.
 *
 * Either strategy can return null when there's nothing useful to say —
 * the section renders no "Related from your brain" block in that case.
 *
 * One LLM call per event combines relevance judgment and summarization.
 */

import { LlmClient } from "../clients/llm.ts";
import { ConsiderationResult, SemanticSearch } from "./semantic-search.ts";

export interface EventForSynthesis {
  summary: string;
  description: string;
  location: string;
}

export interface SynthesizedConsiderations {
  /** 1–3 sentence event-specific brief generated by the LLM. */
  summary: string;
  /** How many brain items informed the synthesis (for the footer). */
  sourceCount: number;
}

export interface SynthesizerOptions {
  /** Candidates to retrieve before synthesis. Default 8. */
  candidatePoolSize?: number;
  /** Minimum cosine similarity for embedding pass. Default 0.5. */
  similarityThreshold?: number;
  /** Max tokens for the synthesis completion. Default 220. */
  synthesisMaxTokens?: number;
}

export class ConsiderationsSynthesizer {
  constructor(
    private readonly semantic: SemanticSearch,
    private readonly llm: LlmClient,
    private readonly opts: SynthesizerOptions = {},
  ) {}

  async forEvent(event: EventForSynthesis): Promise<SynthesizedConsiderations | null> {
    const kind = classifyEvent(event.summary);

    const candidates = kind.type === "birthday" && kind.personName
      ? await this.gatherBirthdayCandidates(kind.personName)
      : await this.gatherGenericCandidates(event);

    const filtered = this.dedupe(candidates);
    if (filtered.length === 0) return null;

    const prompt = kind.type === "birthday" && kind.personName
      ? this.buildBirthdayPrompt(kind.personName, filtered)
      : this.buildGenericPrompt(event, filtered);

    const reply = await this.llm.chat({
      prompt,
      maxTokens: this.opts.synthesisMaxTokens ?? 220,
      temperature: 0.3,
      timeoutMs: 30_000,
    });
    if (!reply) return null;

    if (isNoneVerdict(reply)) return null;

    return { summary: reply.trim(), sourceCount: filtered.length };
  }

  // ─── Candidate gathering ────────────────────────────────────────────────

  private async gatherBirthdayCandidates(name: string): Promise<ConsiderationResult[]> {
    const pool = this.opts.candidatePoolSize ?? 8;
    const threshold = this.opts.similarityThreshold ?? 0.5;
    // Three angles. Each is a separate embedding so we don't conflate
    // "gift ideas" with the person's name into a fuzzy single vector.
    const queries = [
      `gift ideas for ${name}; what ${name} likes; things ${name} wants`,
      `${name} hobbies interests personality preferences`,
      `${name}`,
    ];
    const results = await Promise.all(
      queries.map((q) => this.semantic.findRelated(q, { k: pool, threshold })),
    );
    return results.flat();
  }

  private async gatherGenericCandidates(event: EventForSynthesis): Promise<ConsiderationResult[]> {
    const pool = this.opts.candidatePoolSize ?? 8;
    const threshold = this.opts.similarityThreshold ?? 0.5;
    const query = [event.summary, event.location, event.description]
      .filter(Boolean)
      .join(". ")
      .slice(0, 800);
    return await this.semantic.findRelated(query, { k: pool, threshold });
  }

  private dedupe(candidates: ConsiderationResult[]): ConsiderationResult[] {
    const seen = new Set<number>();
    const out: ConsiderationResult[] = [];
    // Sort by descending similarity so the strongest match wins on dedup.
    for (const c of [...candidates].sort((a, b) => b.similarity - a.similarity)) {
      if (seen.has(c.id)) continue;
      seen.add(c.id);
      out.push(c);
    }
    const pool = this.opts.candidatePoolSize ?? 8;
    return out.slice(0, pool);
  }

  // ─── Prompts ────────────────────────────────────────────────────────────

  private buildBirthdayPrompt(name: string, candidates: ConsiderationResult[]): string {
    const numbered = candidates
      .map((c, i) => `${i + 1}. [${c.source ?? "brain"}] ${c.snippet}`)
      .join("\n");
    return `The user has ${name}'s birthday coming up and is considering a gift.

Items pulled from the user's brain that mention ${name} OR match search terms about them:
${numbered}

═══ CRITICAL GROUNDING RULES (read carefully) ═══

1. Many of these items are about the USER's OWN research, interests, or activities — NOT about ${name}. The items came up because they share keywords with the search, not because they reveal anything about ${name}.

2. Only include details that are EXPLICITLY stated about ${name} in a source item. For each claim you might make, you must be able to point to a specific item that LITERALLY states it about ${name} (e.g. "${name} likes X", "${name} mentioned wanting Y", "${name} is into Z").

3. DO NOT extrapolate. If an item shows the user researched LEGO castles, that does NOT mean ${name} likes LEGO castles. If an item mentions StarCraft, that does NOT mean ${name} plays StarCraft. The user's interests are not ${name}'s interests.

4. DO NOT assume names overlap with preferences. An item that mentions ${name} in a work email, a directions search, or a passing reference does NOT reveal their hobbies.

5. DO NOT fabricate or invent specific gift suggestions (e.g. "AeroPress", "modeling supplies"). If the items don't show ${name} wants something specific, don't suggest it.

═══ DECISION ═══

If you cannot identify at least one item that EXPLICITLY reveals something about ${name}'s preferences, hobbies, values, or stated wants:
  → Output: none

If you can identify explicit person-specific signal:
  → Output: 1–2 sentences grounded ONLY in what the items literally state. Name the items implicitly through the facts (e.g. "${name} has mentioned X" not "item 3 says X").

The expected output for most people is "none" — the user hasn't yet captured person-specific notes for them. That's correct; silence is better than fabrication.`;
  }

  private buildGenericPrompt(event: EventForSynthesis, candidates: ConsiderationResult[]): string {
    const numbered = candidates
      .map((c, i) => `${i + 1}. [${c.source ?? "brain"}] ${c.snippet}`)
      .join("\n");
    return `The user has this upcoming calendar event:
Title: ${event.summary}${event.location ? `\nLocation: ${event.location}` : ""}${event.description ? `\nDescription: ${event.description.slice(0, 240)}` : ""}

Items from the user's brain that semantic search picked as potentially related:
${numbered}

═══ CRITICAL GROUNDING RULES (read carefully) ═══

1. Only present facts EXPLICITLY stated in the source items. Do not infer, extrapolate, or assume implications that aren't there.

2. Treat any "personal status" facts (relationships, ages, roles) in the items as potentially STALE. An item from 2018 saying "X is Y's guardian" does NOT mean X is still Y's guardian today. Do not suggest implications of stale facts as if they're current ("they may need to be present", "they're likely responsible for").

3. Do not invent suggestions or implications. If an item shows the user navigated to a DMV in 2021, that is useful as familiarity context — it does NOT mean the user should do something specific now. Just state the fact ("you've navigated to this office before").

4. Distinguish the USER from event participants. If an item shows the user's own search, navigation, or interest, attribute it to the USER, not to a person named in the event.

═══ DECISION ═══

If items have at least one CONCRETE, CURRENT, EXPLICITLY-STATED connection to the event:
  → Output: 1–3 sentences of synthesis grounded ONLY in what the items literally state. Be specific about what you're surfacing (e.g. "Your past DMV navigation logs..." not "It might help with logistics").

If items only have surface keyword overlap, stale facts, or speculative implications:
  → Output: none

Default to "none" when in doubt. The user prefers silence over fabricated context.`;
  }
}

// ─── "none" verdict detection ──────────────────────────────────────────────
//
// The LLM sometimes obeys "respond with 'none'" by writing a full
// explanation ending in "...none". We treat the bare word AND the
// trailing-"none" pattern as a null verdict. Avoid pattern-matching
// "no useful signal"-style phrases — they catch legitimate syntheses
// too (e.g. "...so no additional prep is needed", which is useful
// context, not an absence).

const NONE_TRAIL = /\bnone\.?\s*$/i;

function isNoneVerdict(reply: string): boolean {
  const trimmed = reply.trim();
  if (trimmed.length === 0) return true;
  const lower = trimmed.toLowerCase();
  if (lower === "none" || lower === "none.") return true;
  if (lower.startsWith("none.") || lower.startsWith("none ")) return true;
  // Trailing "none" — common when the LLM writes an explanation
  // before delivering the verdict.
  if (NONE_TRAIL.test(lower)) return true;
  return false;
}

// ─── Event-type classification ─────────────────────────────────────────────

export interface EventClassification {
  type: "birthday" | "generic";
  personName?: string;
}

/**
 * Detect whether the event is a birthday/anniversary and pull out the
 * subject's name. Handles common phrasings:
 *   "James Murphy's birthday" → birthday, "James Murphy"
 *   "Esme Schuldes's birthday" → birthday, "Esme Schuldes"
 *   "Dads bday" → birthday, "Dad"
 *   "Birthday party for Chris" → birthday, "Chris"
 */
export function classifyEvent(summary: string): EventClassification {
  const trimmed = summary.trim();
  const milestoneWords = "birthday|bday|b-day|anniversary";

  // "<Name>'s birthday" or "<Name>s bday"
  const possessive = new RegExp(`^(.+?)['’]?s\\s+(${milestoneWords})`, "i");
  let m = trimmed.match(possessive);
  if (m && m[1].length >= 2) {
    return { type: "birthday", personName: m[1].trim() };
  }

  // "Birthday [party] for <Name>"
  const forPattern = new RegExp(`(?:${milestoneWords})(?:\\s+party)?\\s+for\\s+(.+)`, "i");
  m = trimmed.match(forPattern);
  if (m && m[1].length >= 2) {
    return { type: "birthday", personName: m[1].trim() };
  }

  // Bare keyword without a name (e.g. "Birthday cake pickup") — still
  // treat as generic; we'd have nothing useful to query for.
  return { type: "generic" };
}
